[package]
name = "serde_rusqlite"
version = "0.33.1"
edition = "2018"
description = "Serialize/deserialize rusqlite rows"
keywords = ["serde", "sqlite", "rusqlite", "serialization", "deserialization"]
categories = ["database", "encoding"]
authors = ["Pro <twisted.fall@gmail.com>"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/serde_rusqlite"
repository = "https://github.com/twistedfall/serde_rusqlite"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rusqlite = "0.29"
serde = "1.0"

[dev-dependencies]
serde_bytes = "0.11"
serde_derive = "1.0"
